### ISSUE TITLE
Redundant metric prefixes/suffixes on the performance chart

### ISSUE THREAD

**Issue by ghost** [dangreco/edgy#1]
Hi Daniel!

The performance chart
![the performance chart](https://raw.githubusercontent.com/dangreco/edgy/master/examples/Performance.jpg) has <i>milli</i>seconds as the unit for the duration axis. However, the actual values are suffixed with <i>k</i>s. Thus, the _milli_ prefix cancels the _k_ suffix. The chart would be clearer if milliseconds were changed to just seconds.

**Comment by dangreco** [comment]
I removed the suffix from the axis and changed the unit to seconds. 
Thanks for the input!!!

**Comment by dangreco** [comment]
I fixed the units/suffix. 
Thanks for the input!
(Not sure how to properly close issue haha)

**Comment by ghost** [comment]
@dangreco You might also add a LICENSE file to the repository to make the clear what the license is, because although there is a `license` field in `Cargo.toml`, it's still not clear does it apply to the GitHub repository as opposed to the create from crates.io.
